name: Node.js CI

on:
  push:
    branches: *
  pull_request:
    branches: *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: Install Dependencies
        run: npm install

      - name: Set environment variables
        run: echo "SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }}" >> $GITHUB_ENV

      - name: Run Tests
        run: npm test
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }} # Pass the secret to the tests
